name: Flutter CI

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2

  - uses: subosito/flutter-action@v1
    with:
      channel: 'stable'

  - name: Install dependencies
    run: flutter pub get
    working-directory: ./online_mufti_final

  - name: Build APK
    run: flutter build apk --release
    working-directory: ./online_mufti_final

  - name: Upload artifact
    uses: actions/upload-artifact@v2
    with:
      name: app-release.apk
      path: ./online_mufti_final/build/app/outputs/flutter-apk/app-release.apk
